# Generated by Django 5.1.3 on 2025-04-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('shipment_content_type', models.CharField(max_length=20)),
                ('freight_type', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('city_of_departure', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
